module.exports = [
    "Glissa, a Traidora",
    "Fera Interior",
    "Nucleo de Phyrexia",
    "Barril de Mimica",
    "Escraviza-Mentes",
    "Magibomba Niilista",
    "Replica de Silvoque",
    "Pomar Exotico",
    "Capsula do Executor",
    "Saqueador Saco-de-Carne",
    "Panorama de Jund",
    "Frasco de Outro Lugar",
    "Bosque Vivido",
    "Pantano Vivido",
    "Confim Outonal",
    "Sextante Farpado",
    "Busca Longinqua",
    "Sinete Golgari",
    "Terrarion",
    "Relogio de Agouros",
    "Chapeamento Craniano",
    "Bijuteria do Viajante",
    "Mascara da Nemese",
    "Esfera Cromatica",
    "Garras Esmiucadoras",
    "Arco Longo Viridiano",
    "Chamado ao Tumulo",
    "Maleta de Remedios",
    "Pedra da Mente",
    "Fornalha Phyrexiana",
    "Botas Pe-ligeiro",
    "Anel de Xathrid",
    "Entreposto",
    "Olhar de Granito",
    "Alma de Nova Phyrexia",
    "Esfera do Comandante",
    "Executor Impiedoso",
    "Arquivo de Edro",
    "Colosso de Serralheria",
    "Cronometro Perpetuo",
    "Inspetor da Fundicao",
    "Mestra das Marionetes",
    "Arrastador de Sucata",
    "Implemento de Ferocidade",
    "Fome de Vona",
    "Aquisicao do Mentor",
    "Escrituras Phyrexianas",
    "Familiar de Jhoira",
    "Despedida Final",
    "Golem Meteorico",
    "Varinha Transmogrificadora",
    "Lich do Reino Subterraneo",
    "Empesteiro",
    "Globo da Guilda",
    "Recombinador do Ferro-velho",
    "Talisma da Resiliencia",
    "Salvadego da Ruina",
    "Grismold, Semeador do Pavor",
    "Ovo de Ouro"
]