module.exports = [
    "Fera Interior",
    "Nucleo de Phyrexia",
    // "Barril de Mimica",
    // "Escraviza-Mentes",
    // "Magibomba Niilista",
    // "Bomba de Catraca",
    // "Replica de Silvoque",
    // "Terras em Desenvolvimento",
    // "Pomar Exotico",
    // "Capsula do Executor",
    // "Saqueador Saco-de-Carne",
    // "Panorama de Jund",
    // "Frasco de Outro Lugar",
    // "Bosque Vivido",
    // "Pantano Vivido",
    // "Confim Outonal",
    // "Vastidao Morfoterrena",
    // "Sextante Farpado",
    // "Falange do Submundo",
    // "Busca Longinqua",
    // "Sinete Golgari",
    // "Caldeira de Praga",
    // "Terrarion",
    // "Relogio de Agouros",
    // "Bijuteria do Conjurador",
    // "Chapeamento Craniano",
    // "Bijuteria do Viajante",
    // "Mascara da Nemese",
    // "Esfera Cromatica",
    // "Magibomba de Centelha de Vida",
    // "Magibomba de Necrogenio",
    // "Garras Esmiucadoras",
    // "Arco Longo Viridiano",
    // "Chamado ao Tumulo",
    // "Tutor Diabolico",
    // "Maleta de Remedios",
    // "Crescimento Exuberante",
    // "Pedra da Mente",
    // "Fornalha Phyrexiana",
    // "Botas Pe-ligeiro",
    // "Disco de Nevinyrral",
    // "Anel de Xathrid",
    // "Entreposto",
    // "Ordens de Jarad",
    // "Triturador de Codices",
    // "Portao da Guilda Golgari",
    // "Olhar de Granito",
    // "Cavalo de Acros",
    // "Alma de Nova Phyrexia",
    // "Clareira na Selva",
    // "Esfera do Comandante",
    // "Executor Impiedoso",
    // "Arquivo de Edro",
    // "Pomar Hediondo",
    // "Colosso de Serralheria",
    // "Cronometro Perpetuo",
    // "Inspetor da Fundicao",
    // "Mestra das Marionetes",
    // "Arrastador de Sucata",
    // "Implemento de Ferocidade",
    // "Fome de Vona",
    // "Aquisicao do Mentor",
    // "Escrituras Phyrexianas",
    // "Familiar de Jhoira",
    // "Despedida Final",
    // "Golem Meteorico",
    // "Varinha Transmogrificadora",
    // "Lich do Reino Subterraneo",
    // "Empesteiro",
    // "Globo da Guilda",
    // "Recombinador do Ferro-velho",
    // "Talisma da Resiliencia",
    // "Salvadego da Ruina",
    // "Grismold, Semeador do Pavor",
    // "Ovo de Ouro"
]